// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02MtHoFat0aXJjwc8Q_EphlE0t5gYhlQ',
    appId: '1:78530280765:web:a94b72adb650e04808d954',
    messagingSenderId: '78530280765',
    projectId: 'notify-demo-8ac47',
    authDomain: 'notify-demo-8ac47.firebaseapp.com',
    storageBucket: 'notify-demo-8ac47.appspot.com',
    measurementId: 'G-H2VWS1F1CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6xb13a9xk6AMHRGrOORYwagHqv1T2N54',
    appId: '1:78530280765:android:ed07cd857813676708d954',
    messagingSenderId: '78530280765',
    projectId: 'notify-demo-8ac47',
    storageBucket: 'notify-demo-8ac47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbdKd2MutoOT8H0qNuOU3xsqvjagbCl28',
    appId: '1:78530280765:ios:315fbe340474e4d008d954',
    messagingSenderId: '78530280765',
    projectId: 'notify-demo-8ac47',
    storageBucket: 'notify-demo-8ac47.appspot.com',
    iosClientId: '78530280765-m8rfl1hpk9k14eq234glj3rgherr337d.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifyDemo',
  );
}
